### ISSUE TITLE
Add .php_cs

### ISSUE THREAD

**Issue by joelwurtz** [php-http/boilerplate#1]
Maybe adding a php_cs fixer file will help for all our libraries, (we can then just run the fixer on each of the project)

I can prepare one with some rules i generally use and we can discuss each of them if you want them or not.

**Comment by sagikazarmark** [comment]
Sounds like a plan. Actually, I was also thinking about it, but I never had the time for it.

**Comment by joelwurtz** [comment]
Fixed by #3
