### ISSUE TITLE
PHPDoc order

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/boilerplate#14]
In the past I ordered phpdoc like this: params first, then return and throws at the end.

However [phpdoc_order](https://styleci.readme.io/docs/fixers#phpdoc_order) fixer follows param, throws, return order.

Honestly, I followed the upper way because I thought that's some kind of standard. Isn't it?

/cc @dbu

**Comment by dbu** [comment]
i have never seen that order styleci seems to want. i always had param,
return, throws as well. i would prefer to keep it that way, seems so
much more logic.

**Comment by sagikazarmark** [comment]
This means, that we turn off any ordering (param, return, throws).

**Comment by dbu** [comment]
okay. i think we will notice during review when they are out of order.
